name: unity-build-impl
description: 'Unityのビルドを行う'
inputs:
  environment:
    description: 'ビルド時の環境'
    required: true
  platform:
    description: 'ビルド対象とするプラットフォーム'
    required: true
  build_id:
    description: 'アーカイブ時のビルドID指定'
    required: false
  enable_notify:
    description: 'ビルド完了時に通知を出すかどうか'
    required: true
  is_upload:
    description: 'ビルド完了後にアプリをAppCenterにアップロードするかどうか'
    required: true
outputs:
  elapsed-time:
    description: 'ビルドにかかった時間'
    value: ${{steps.build.outputs.elapsed-time}}
  platform:
    description: 'ビルド対象プラットフォーム'
    value: ${{steps.build.outputs.platform}}
  succeeded:
    description: 'ビルドが成功したか？'
    value: ${{steps.build.outputs.succeeded}}
runs:
  using: "composite"
  steps:
    - name: Unity - Build
      shell: bash
      run: |
        cd tools/
        ./apps/up-tools-container.sh $RUNNER_OS
        ./apps/exec-tools-container.sh bash -c "cd commons/fastlane && \
                                           bundle exec fastlane \
                                              ${{inputs.platform}} \
                                              unity_build \
                                              environment:${{inputs.environment}} \
                                              upload_to_appcenter:${{inputs.is_upload}} \
                                              enable_notify:${{inputs.enable_notify}}"
    - name: Github Actions - Show GITHUB_ENV
      id: build
      shell: bash
      run: |
        cat $GITHUB_ENV
        echo "::set-output name=elapsed-time::${{env.UNITY_BUILD_RESULT_ELAPSED_TIME}}"
        echo "::set-output name=platform::${{env.UNITY_BUILD_RESULT_PLATFORM}}"
        echo "::set-output name=succeeded::${{env.UNITY_BUILD_RESULT_SUCCEEDED}}"