name: unity-build-impl
description: 'Unityのビルドを行う'
inputs:
  environment:
    description: 'ビルド時の環境'
    required: true
  platform:
    description: 'ビルド対象とするプラットフォーム'
    required: true
  build_id:
    description: 'アーカイブ時のビルドID指定'
    required: false
  enable_notify:
    description: 'ビルド完了時に通知を出すかどうか'
    required: true
  is_upload:
    description: 'ビルド完了後にアプリをAppCenterにアップロードするかどうか'
    required: true
outputs:
  result-json:
    description: "jsonフォーマットのビルド結果"
    value: ${{steps.build.outputs.json}}
runs:
  using: "composite"
  steps:
    - name: Unity - Build
      shell: bash
      run: |
        # 汎用向けコンテナのセットアップ
        git submodule update --init tools/commons
        cd tools/commons/
        git fetch
        git switch -C main origin/main
        chmod 775 ./run-client-container.sh

        # アプリケーション固有を含めたコンテナセットアップ
        cd ../
        chmod 775 ./up-tools-container.sh
        ./up-tools-container.sh $RUNNER_OS
        chmod 775 ./exec-tools-container.sh
        ./exec-tools-container.sh bash -c "cd commons/fastlane && \
                                           bundle exec fastlane \
                                              ${{inputs.platform}} \
                                              unity_build \
                                              environment:${{inputs.environment}} \
                                              upload_to_appcenter:${{inputs.is_upload}} \
                                              enable_notify:${{inputs.enable_notify}}"
    - name: Github Actions - Show GITHUB_ENV
      id: build
      shell: bash
      run: |
        cat $GITHUB_ENV
        echo "::set-output name=json::${{env.UNITY_BUILD_RESULT_JSON}}"