name: unity-activate-license
on:
  workflow_call:
    inputs:
      unity_version: 
        description: 'Unity Version'
        required: true
        default: 2021.3.8f1
        type: string
jobs:
  activate-license:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Unity - Actiate License
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ inputs.unity_version }}
      - name: Unity - Expose Activate License
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}