name: unity-build-all
on:
  workflow_call:
    inputs:
      environment:
        description: '環境'
        required: true
        default: 'Development'
        type: string
      is_upload:
        description: 'AppCenterにアップロードするかどうか'
        required: true
        default: false
        type: boolean
      enable_notify:
        description: '通知を飛ばすか'
        required: true
        default: true
        type: boolean
jobs:
  show-context:
    runs-on: self-hosted
    steps:
      - name: Git - checkout
        uses: actions/checkout@v3
      - name: Composite Action - Show Context
        uses: sim-mokomo/MokomoGamesLib_GithubActions/.github/actions/show-context@main
  ios-build:
    runs-on: [self-hosted, macos]
    outputs:
      elapsed-time: ${{steps.unity-build.outputs.elapsed-time}}
      platform: ${{steps.unity-build.outputs.platform}}
      succeeded: ${{steps.unity-build.outputs.succeeded}}
    steps:
      - name: Git - checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Composite Action - iOS Build
        uses: sim-mokomo/MokomoGamesLib_GithubActions/.github/actions/unity-build@main
        id: unity-build
        with:
          environment: ${{inputs.environment}}
          platform: ios
          enable_notify: false
          is_upload: ${{inputs.is_upload}}
  android-build:
    runs-on: [self-hosted, windows]
    outputs:
      elapsed-time: ${{steps.unity-build.outputs.elapsed-time}}
      platform: ${{steps.unity-build.outputs.platform}}
      succeeded: ${{steps.unity-build.outputs.succeeded}}
    steps:
      - name: Git - checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Composite Action - Android Build
        uses: sim-mokomo/MokomoGamesLib_GithubActions/.github/actions/unity-build@main
        id: unity-build
        with:
          environment: ${{inputs.environment}}
          platform: android
          enable_notify: false
          is_upload: ${{inputs.is_upload}}
  notify-result:
    runs-on: [self-hosted]
    needs: [ios-build, android-build]
    if: always()
    steps:
      - name: Git - checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Slack - Notify Build Result
        shell: bash
        run: |
          cd tools/
          ./apps/up-tools-container.sh $RUNNER_OS
          ./apps/exec-tools-container.sh bash -c 'cd commons/fastlane && \
                                                  bundle exec fastlane \
                                                    notify_unity_build_result_all_from_github_action \
                                                    ios_build_elapsed_time:${{needs.ios-build.outputs.elapsed-time}} \
                                                    ios_build_platform:${{needs.ios-build.outputs.platform}} \
                                                    ios_build_succeeded:${{needs.ios-build.outputs.succeeded}} \
                                                    android_build_elapsed_time:${{needs.android-build.outputs.elapsed-time}} \
                                                    android_build_platform:${{needs.android-build.outputs.platform}} \
                                                    android_build_succeeded:${{needs.android-build.outputs.succeeded}}'