name: unity-editor-test
on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        required: true
jobs:
  run-editor-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # 個人利用前提なのでプロジェクトフォルダの指定は固定
          projectPath: ./client
          githubToken: ${{ secrets.GITHUB_TOKEN }}